name: CI

on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main
      - master

env:
  CI: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: volta-cli/action@v1
    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 6.32.1
        run_install: true
    - name: ESLint
      run: yarn lint:js
    - name: Types
      run: yarn tsc --noEmit --skipLibCheck
    - uses: wagoid/commitlint-github-action@v4.1.11
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  publish:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [lint]

    steps:
    - uses: actions/checkout@v3
    - uses: volta-cli/action@v1
    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 6.32.1
        run_install: true
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: pnpm exec semantic-release
